name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodeVersion:
          - 12
          - 14
          - 16
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-build-node_${{ matrix.nodeVersion }}-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.OS}}-build-node_${{ matrix.nodeVersion }}-*
      - name: yarn berry
        run: yarn set version berry
      - run: yarn install
      - run: yarn test

